### ISSUE TITLE
Force Figure Position in Scholarly Markdown?

### ISSUE THREAD

**Issue by dnguyen85** [timtylin/scholdoc#11]
Hi, I was wondering if there is a syntax in Scholarly Markdown to force a figure position (for pdf and tex outputs). Such syntax should ideally attach placement properties (`htbp`, etc.) to the figure float environment. 

Is this supported in the current `scholdoc`?

Thanks,
Dan

**Comment by timtylin** [comment]
Hi Dan! Thanks for your interest in Scholdoc.

The current default for LaTeX is to use `htbp` placement. [This is specified in the default Scholdoc latex template](https://github.com/timtylin/scholdoc-templates/blob/master/scholmdTemplate.latex#L152) using the `floatplacement` command from the `float` package

```
\floatplacement{figure}{htbp}
```

To over-ride this, note that the default latex template has a bunch of places where you can inject your own latex commands (via special variables) without having to use a new template. The most useful is probably [the `latex-header-includes` variable](https://github.com/timtylin/scholdoc-templates/blob/master/scholmdTemplate.latex#L250) which is immediately before `\begin{document}`.

To change figure placement to, say, `tbp`, you can add the following to your YAML metadata block in your _scholdoc markdown document_

```
---
latex-header-includes:
  - \floatplacement{figure}{tbp}
---
```

Hope that helps.

Tim

**Comment by dnguyen85** [comment]
Hi Tim, that is extremely helpful. Thank you so much for your effort in developing and maintaining such a great authoring tool as `scholdoc`. Your answer above gives me some clear instructions on how to customize the latex output I want. I recently adopt `scholdoc` for some writing assignments and must say it takes away all the pains in using `pandoc`.

Best Regards,
Dan
